name: Publish Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - id: slack
        uses: slackapi/slack-github-action@v1.25.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
        with:
          channel-id: ${{ vars.SLACK_NOTIFICATION_CHANNEL_ID }}
          payload: |
            {
              "text": "<https://github.com/${{ github.repository }}|${{ github.repository }}> : Publishing started for tag `${{ github.ref_name }}` (In Progress) - Build Link: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|Click here for build details>",
              "attachments": [
                {
                  "pretext": "Publishing started",
                  "color": "dbab09",
                  "fields": [
                    {
                      "title": "Status",
                      "short": true,
                      "value": "In Progress"
                    }
                  ]
                }
              ]
            }
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create "${{ github.ref_name }}" --title "Release ${{ github.ref_name }}" --generate-notes --latest

      - uses: slackapi/slack-github-action@v1.25.0
        if: always()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
        with:
          channel-id: ${{ vars.SLACK_NOTIFICATION_CHANNEL_ID }}
          update-ts: ${{ steps.slack.outputs.ts }}
          payload: |
            {
              "text": "Repository: <https://github.com/${{ github.repository }}|${{ github.repository }}> - Publishing Status for tag `${{ github.ref_name }}`: ${{ job.status }} - Build Link: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|Click here for build details>",
              "attachments": [
                {
                  "pretext": "Publishing Status: ${{ job.status }}",
                  "color": "${{ job.status == 'success' && '28a745' || 'ff0000' }}",
                  "fields": [
                    {
                      "title": "Status",
                      "short": true,
                      "value": "${{ job.status == 'success' && 'Completed' || 'Failure' }}"
                    }
                  ]
                }
              ]
            }
